[build]
  # Tell Netlify to build from the frontend folder
  base = "frontend"
  command = "npm install && npm run build"
  publish = "frontend/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
